<?php

/**
 * Tema do app mobile por tenant.
 *
 * Persistência (tenant_settings, module = mobile_theme):
 * - template_id: slug do template escolhido
 * - colors: sobrescritas parciais sobre o template
 */
return [
    'default_template_id' => 'default',

    'schema' => [
        'primary' => [
            'label' => 'Cor primária',
            'description' => 'Menu lateral, barra inferior e destaques.',
            'group' => 'marca',
        ],
        'drawer_header_title' => [
            'label' => 'Título do menu',
            'description' => 'Texto "Menu" no topo da sidebar.',
            'group' => 'menu_lateral',
        ],
        'drawer_header_subtitle' => [
            'label' => 'Subtítulo do menu',
            'description' => 'Texto "Acesso rápido" no topo da sidebar.',
            'group' => 'menu_lateral',
        ],
        'drawer_header_icon' => [
            'label' => 'Ícone fechar (header)',
            'description' => 'Ícone X do cabeçalho do menu.',
            'group' => 'menu_lateral',
        ],
        'drawer_section_label' => [
            'label' => 'Labels de seção',
            'description' => 'Textos "NAVEGAÇÃO" e "CONTA".',
            'group' => 'menu_lateral',
        ],
        'menu_button_background' => [
            'label' => 'Fundo do botão',
            'description' => 'Fundo dos itens do menu (Início, Calendário…).',
            'group' => 'botoes_menu',
        ],
        'menu_button_text' => [
            'label' => 'Texto do botão',
            'description' => 'Rótulo dos itens do menu.',
            'group' => 'botoes_menu',
        ],
        'menu_button_icon' => [
            'label' => 'Ícone do botão',
            'description' => 'Ícones dos itens do menu.',
            'group' => 'botoes_menu',
        ],
        'menu_button_icon_background' => [
            'label' => 'Fundo do ícone',
            'description' => 'Círculo atrás do ícone no botão.',
            'group' => 'botoes_menu',
        ],
        'menu_button_chevron' => [
            'label' => 'Seta do botão',
            'description' => 'Chevron (>) dos itens.',
            'group' => 'botoes_menu',
        ],
        'menu_button_active_background' => [
            'label' => 'Fundo botão ativo',
            'description' => 'Item selecionado no menu.',
            'group' => 'botoes_menu',
        ],
        'menu_button_active_text' => [
            'label' => 'Texto botão ativo',
            'description' => 'Rótulo do item selecionado.',
            'group' => 'botoes_menu',
        ],
        'menu_button_active_icon' => [
            'label' => 'Ícone botão ativo',
            'description' => 'Ícone do item selecionado.',
            'group' => 'botoes_menu',
        ],
        'menu_button_active_icon_background' => [
            'label' => 'Fundo ícone ativo',
            'description' => 'Círculo do ícone no item selecionado.',
            'group' => 'botoes_menu',
        ],
        'menu_button_active_chevron' => [
            'label' => 'Seta botão ativo',
            'description' => 'Chevron do item selecionado.',
            'group' => 'botoes_menu',
        ],
        'ink' => [
            'label' => 'Texto forte',
            'description' => 'Títulos nas telas.',
            'group' => 'texto',
        ],
        'text' => [
            'label' => 'Texto',
            'description' => 'Corpo de texto.',
            'group' => 'texto',
        ],
        'muted' => [
            'label' => 'Texto secundário',
            'description' => 'Legendas e metadados.',
            'group' => 'texto',
        ],
        'soft' => [
            'label' => 'Fundo suave',
            'description' => 'Áreas destacadas claras.',
            'group' => 'superficie',
        ],
        'border' => [
            'label' => 'Bordas',
            'description' => 'Divisórias e cards.',
            'group' => 'superficie',
        ],
        'surface' => [
            'label' => 'Superfície',
            'description' => 'Cards e modais.',
            'group' => 'superficie',
        ],
        'background' => [
            'label' => 'Fundo da tela',
            'description' => 'Fundo geral do app.',
            'group' => 'superficie',
        ],
        'tab_bar_inactive' => [
            'label' => 'Tab bar inativa',
            'description' => 'Ícones/textos inativos na barra inferior.',
            'group' => 'marca',
        ],
        'debit' => [
            'label' => 'Alerta / débito',
            'description' => 'Erros e ação Sair.',
            'group' => 'status',
        ],
        'credit' => [
            'label' => 'Sucesso / crédito',
            'description' => 'Estados positivos.',
            'group' => 'status',
        ],
    ],

    'templates' => [
        'default' => [
            'id' => 'default',
            'name' => 'Original (Índigo)',
            'description' => 'Tema padrão do AppEscola.',
            'preview' => ['#4F46E5', '#EEF2FF', '#FFFFFF'],
            'colors' => [
                'primary' => '#4F46E5',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#C7D2FE',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#C7D2FE',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#4F46E5',
                'menu_button_icon' => '#4F46E5',
                'menu_button_icon_background' => '#EEF2FF',
                'menu_button_chevron' => '#4F46E5',
                'menu_button_active_background' => 'rgba(255,255,255,0.14)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.18)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#1E1B4B',
                'text' => '#312E81',
                'muted' => '#64748B',
                'soft' => '#EEF2FF',
                'border' => '#DDE3F5',
                'surface' => '#FFFFFF',
                'background' => '#F6F7FB',
                'tab_bar_inactive' => '#C7D2FE',
                'debit' => '#EF4444',
                'credit' => '#10B981',
            ],
        ],
        'emerald' => [
            'id' => 'emerald',
            'name' => 'Esmeralda',
            'description' => 'Verde vibrante, ideal para identidade natural.',
            'preview' => ['#16A34A', '#DCFCE7', '#FFFFFF'],
            'colors' => [
                'primary' => '#16A34A',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#BBF7D0',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#BBF7D0',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#15803D',
                'menu_button_icon' => '#16A34A',
                'menu_button_icon_background' => '#DCFCE7',
                'menu_button_chevron' => '#16A34A',
                'menu_button_active_background' => 'rgba(255,255,255,0.16)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.2)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#14532D',
                'text' => '#166534',
                'muted' => '#4B5563',
                'soft' => '#DCFCE7',
                'border' => '#BBF7D0',
                'surface' => '#FFFFFF',
                'background' => '#F0FDF4',
                'tab_bar_inactive' => '#BBF7D0',
                'debit' => '#DC2626',
                'credit' => '#059669',
            ],
        ],
        'ocean' => [
            'id' => 'ocean',
            'name' => 'Oceano',
            'description' => 'Azul calmo e profissional.',
            'preview' => ['#0284C7', '#E0F2FE', '#FFFFFF'],
            'colors' => [
                'primary' => '#0284C7',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#BAE6FD',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#BAE6FD',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#0369A1',
                'menu_button_icon' => '#0284C7',
                'menu_button_icon_background' => '#E0F2FE',
                'menu_button_chevron' => '#0284C7',
                'menu_button_active_background' => 'rgba(255,255,255,0.14)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.18)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#0C4A6E',
                'text' => '#075985',
                'muted' => '#64748B',
                'soft' => '#E0F2FE',
                'border' => '#BAE6FD',
                'surface' => '#FFFFFF',
                'background' => '#F0F9FF',
                'tab_bar_inactive' => '#BAE6FD',
                'debit' => '#EF4444',
                'credit' => '#10B981',
            ],
        ],
        'sunset' => [
            'id' => 'sunset',
            'name' => 'Pôr do sol',
            'description' => 'Laranja energético e acolhedor.',
            'preview' => ['#EA580C', '#FFEDD5', '#FFFFFF'],
            'colors' => [
                'primary' => '#EA580C',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#FED7AA',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#FED7AA',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#C2410C',
                'menu_button_icon' => '#EA580C',
                'menu_button_icon_background' => '#FFEDD5',
                'menu_button_chevron' => '#EA580C',
                'menu_button_active_background' => 'rgba(255,255,255,0.16)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.2)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#7C2D12',
                'text' => '#9A3412',
                'muted' => '#78716C',
                'soft' => '#FFEDD5',
                'border' => '#FED7AA',
                'surface' => '#FFFFFF',
                'background' => '#FFF7ED',
                'tab_bar_inactive' => '#FED7AA',
                'debit' => '#DC2626',
                'credit' => '#16A34A',
            ],
        ],
        'ruby' => [
            'id' => 'ruby',
            'name' => 'Rubi',
            'description' => 'Vermelho marcante e moderno.',
            'preview' => ['#DC2626', '#FEE2E2', '#FFFFFF'],
            'colors' => [
                'primary' => '#DC2626',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#FECACA',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#FECACA',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#B91C1C',
                'menu_button_icon' => '#DC2626',
                'menu_button_icon_background' => '#FEE2E2',
                'menu_button_chevron' => '#DC2626',
                'menu_button_active_background' => 'rgba(255,255,255,0.14)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.18)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#7F1D1D',
                'text' => '#991B1B',
                'muted' => '#6B7280',
                'soft' => '#FEE2E2',
                'border' => '#FECACA',
                'surface' => '#FFFFFF',
                'background' => '#FEF2F2',
                'tab_bar_inactive' => '#FECACA',
                'debit' => '#B91C1C',
                'credit' => '#16A34A',
            ],
        ],
        'violet' => [
            'id' => 'violet',
            'name' => 'Violeta',
            'description' => 'Roxo criativo e jovem.',
            'preview' => ['#7C3AED', '#EDE9FE', '#FFFFFF'],
            'colors' => [
                'primary' => '#7C3AED',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#DDD6FE',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#DDD6FE',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#6D28D9',
                'menu_button_icon' => '#7C3AED',
                'menu_button_icon_background' => '#EDE9FE',
                'menu_button_chevron' => '#7C3AED',
                'menu_button_active_background' => 'rgba(255,255,255,0.14)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.18)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#4C1D95',
                'text' => '#5B21B6',
                'muted' => '#6B7280',
                'soft' => '#EDE9FE',
                'border' => '#DDD6FE',
                'surface' => '#FFFFFF',
                'background' => '#F5F3FF',
                'tab_bar_inactive' => '#DDD6FE',
                'debit' => '#EF4444',
                'credit' => '#10B981',
            ],
        ],
        'graphite' => [
            'id' => 'graphite',
            'name' => 'Grafite',
            'description' => 'Neutro elegante para visual corporativo.',
            'preview' => ['#334155', '#F1F5F9', '#FFFFFF'],
            'colors' => [
                'primary' => '#334155',
                'drawer_header_title' => '#FFFFFF',
                'drawer_header_subtitle' => '#CBD5E1',
                'drawer_header_icon' => '#FFFFFF',
                'drawer_section_label' => '#CBD5E1',
                'menu_button_background' => '#FFFFFF',
                'menu_button_text' => '#1E293B',
                'menu_button_icon' => '#334155',
                'menu_button_icon_background' => '#F1F5F9',
                'menu_button_chevron' => '#475569',
                'menu_button_active_background' => 'rgba(255,255,255,0.12)',
                'menu_button_active_text' => '#FFFFFF',
                'menu_button_active_icon' => '#FFFFFF',
                'menu_button_active_icon_background' => 'rgba(255,255,255,0.16)',
                'menu_button_active_chevron' => '#FFFFFF',
                'ink' => '#0F172A',
                'text' => '#1E293B',
                'muted' => '#64748B',
                'soft' => '#F1F5F9',
                'border' => '#E2E8F0',
                'surface' => '#FFFFFF',
                'background' => '#F8FAFC',
                'tab_bar_inactive' => '#CBD5E1',
                'debit' => '#DC2626',
                'credit' => '#16A34A',
            ],
        ],
    ],
];
