-- Catálogo de tipos de prova (espelha database/seeders/ExamTypeSeeder.php)
-- Uso: mysql ... < exam_types_seed.sql
-- Ou: php artisan db:seed --class=ExamTypeSeeder

SET NAMES utf8mb4;

INSERT INTO exam_types (slug, label, sort_order, is_active, created_at, updated_at) VALUES
('enem', 'ENEM', 0, 1, NOW(), NOW()),
('sisu', 'SISU', 1, 1, NOW(), NOW()),
('prouni', 'PROUNI', 2, 1, NOW(), NOW()),
('fies', 'FIES', 3, 1, NOW(), NOW()),
('vestibular-tradicional', 'Vestibular Tradicional', 4, 1, NOW(), NOW()),
('vestibular-seriado', 'Vestibular Seriado', 5, 1, NOW(), NOW()),
('vestibular-agendado', 'Vestibular Agendado', 6, 1, NOW(), NOW()),
('vestibular-ead', 'Vestibular EAD', 7, 1, NOW(), NOW()),
('vestibular-medicina', 'Vestibular de Medicina', 8, 1, NOW(), NOW()),
('ifal', 'IFAL', 9, 1, NOW(), NOW()),
('ifpe', 'IFPE', 10, 1, NOW(), NOW()),
('ifrn', 'IFRN', 11, 1, NOW(), NOW()),
('ifpb', 'IFPB', 12, 1, NOW(), NOW()),
('ifba', 'IFBA', 13, 1, NOW(), NOW()),
('ifce', 'IFCE', 14, 1, NOW(), NOW()),
('if-sertao-pe', 'IF Sertão-PE', 15, 1, NOW(), NOW()),
('cpm', 'CPM (Colégio da Polícia Militar)', 16, 1, NOW(), NOW()),
('colegio-militar', 'Colégio Militar', 17, 1, NOW(), NOW()),
('etec-escolas-tecnicas', 'ETEC/Escolas Técnicas', 18, 1, NOW(), NOW()),
('concurso-prefeitura', 'Concurso Prefeitura', 19, 1, NOW(), NOW()),
('concurso-camara-municipal', 'Concurso Câmara Municipal', 20, 1, NOW(), NOW()),
('concurso-estadual', 'Concurso Estadual', 21, 1, NOW(), NOW()),
('concurso-federal', 'Concurso Federal', 22, 1, NOW(), NOW()),
('pm-policia-militar', 'PM (Polícia Militar)', 23, 1, NOW(), NOW()),
('bombeiros', 'Bombeiros', 24, 1, NOW(), NOW()),
('pc-policia-civil', 'PC (Polícia Civil)', 25, 1, NOW(), NOW()),
('prf', 'PRF', 26, 1, NOW(), NOW()),
('pf', 'PF', 27, 1, NOW(), NOW()),
('guarda-municipal', 'Guarda Municipal', 28, 1, NOW(), NOW()),
('banco-do-brasil', 'Banco do Brasil', 29, 1, NOW(), NOW()),
('caixa-economica', 'Caixa Econômica', 30, 1, NOW(), NOW()),
('banco-do-nordeste', 'Banco do Nordeste', 31, 1, NOW(), NOW()),
('correios', 'Correios', 32, 1, NOW(), NOW()),
('inss', 'INSS', 33, 1, NOW(), NOW()),
('receita-federal', 'Receita Federal', 34, 1, NOW(), NOW()),
('tribunal-de-justica', 'Tribunal de Justiça', 35, 1, NOW(), NOW()),
('ministerio-publico', 'Ministério Público', 36, 1, NOW(), NOW()),
('defensoria-publica', 'Defensoria Pública', 37, 1, NOW(), NOW()),
('esa', 'ESA', 38, 1, NOW(), NOW()),
('espcex', 'EsPCEx', 39, 1, NOW(), NOW()),
('epcar', 'EPCAR', 40, 1, NOW(), NOW()),
('marinha', 'Marinha', 41, 1, NOW(), NOW()),
('aeronautica', 'Aeronáutica', 42, 1, NOW(), NOW()),
('exercito', 'Exército', 43, 1, NOW(), NOW()),
('residencia-medica', 'Residência Médica', 44, 1, NOW(), NOW()),
('residencia-multiprofissional', 'Residência Multiprofissional', 45, 1, NOW(), NOW()),
('concurso-professor', 'Concurso Professor', 46, 1, NOW(), NOW()),
('concurso-saude', 'Concurso Saúde', 47, 1, NOW(), NOW()),
('concurso-administrativo', 'Concurso Administrativo', 48, 1, NOW(), NOW()),
('concurso-ti', 'Concurso TI', 49, 1, NOW(), NOW()),
('concurso-fiscal', 'Concurso Fiscal', 50, 1, NOW(), NOW()),
('concurso-juridico', 'Concurso Jurídico', 51, 1, NOW(), NOW()),
('concurso-legislativo', 'Concurso Legislativo', 52, 1, NOW(), NOW()),
('concurso-universidades-federais', 'Concurso Universidades Federais', 53, 1, NOW(), NOW()),
('concurso-institutos-federais', 'Concurso Institutos Federais', 54, 1, NOW(), NOW()),
('presencial', 'Presencial', 55, 1, NOW(), NOW()),
('custom', 'Personalizado', 56, 1, NOW(), NOW()),
('vestibular', 'Vestibular', 57, 0, NOW(), NOW()),
('fuvest', 'FUVEST', 58, 0, NOW(), NOW()),
('concurso', 'Concurso', 59, 0, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    label = VALUES(label),
    sort_order = VALUES(sort_order),
    is_active = VALUES(is_active),
    updated_at = NOW();
