import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../theme';

export function createFinanceiroStyles(colors: ThemeColors) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F6F7FB' },
  content: { padding: 14, paddingTop: 16, paddingBottom: 32 },
  headerWrap: {
    backgroundColor: '#FBFAFF',
    paddingHorizontal: 20,
    paddingBottom: 18,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    shadowColor: '#7C3AED',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  headerGlowPrimary: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    right: -104,
    top: -150,
    backgroundColor: '#F0E9FF',
    opacity: 0.92,
  },
  headerGlowSecondary: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    left: -76,
    top: 58,
    backgroundColor: '#F7F2FF',
    opacity: 0.98,
  },
  enrollmentCardWrap: {
    marginTop: 12,
    marginBottom: 4,
  },
  headerTituloRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 14,
    paddingBottom: 14,
  },
  headerTituloConteudo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  headerTituloIcone: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitulo: { fontSize: 22, fontWeight: '800', color: '#111827' },
  
  // Resumo
  resumoGrid: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#EEE8FF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: 8,
  },
  resumoItem: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingVertical: 13,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  resumoIcone: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 7,
  },
  resumoIconeAtrasado: { backgroundColor: '#FEF2F2' },
  resumoIconeAtual: { backgroundColor: '#FFF7ED' },
  resumoIconePago: { backgroundColor: '#ECFDF5' },
  resumoItemLabel: { fontSize: 12, color: '#64748B', marginBottom: 3, fontWeight: '800' },
  resumoItemValor: { fontSize: 18, fontWeight: '900', marginBottom: 2 },
  resumoItemQtd: { fontSize: 11, color: '#64748B', fontWeight: '700', textAlign: 'center' },
  divisorResumo: { display: 'none' },
  
  // Seções
  secaoCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  secaoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  secaoIcone: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secaoIconeAtrasada: {
    backgroundColor: '#FEF2F2',
  },
  secaoIconeAtual: {
    backgroundColor: colors.soft,
  },
  secaoIconePaga: {
    backgroundColor: '#ECFDF5',
  },
  secaoTituloWrap: {
    flex: 1,
    minWidth: 0,
  },
  secaoTitulo: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.ink,
  },
  secaoSubtitulo: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 1,
  },
  
  // Cards de cobrança
  cobrancaCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cobrancaHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 10,
  },
  cobrancaIcone: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cobrancaInfo: { flex: 1, minWidth: 0 },
  cobrancaDescricao: { fontSize: 15, fontWeight: '700', color: colors.ink, marginBottom: 4, lineHeight: 19 },
  cobrancaData: { fontSize: 12, color: colors.muted, fontWeight: '500' },
  cobrancaMeta: { alignItems: 'flex-end', marginLeft: 6 },
  cobrancaStatus: {
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  cobrancaStatusPago: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
  },
  cobrancaValor: { fontSize: 16, fontWeight: '700', color: colors.ink },
  
  // Ações/Botões de cobrança
  acoesBotoes: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  botaoAcao: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  botaoPagarPrimario: { backgroundColor: colors.primary, flex: 1, justifyContent: 'center' },
  botaoAcaoPrimario: { backgroundColor: colors.primary, flex: 1, justifyContent: 'center' },
  botaoAcaoSecundario: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.primary },
  botaoAcaoTexto: { fontSize: 13, fontWeight: '700', color: colors.surface },
  
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.34)',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
    paddingHorizontal: 16,
    paddingBottom: 22,
    maxHeight: '92%',
  },
  modalHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#CBD5E1',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 16,
  },
  modalTituloWrap: {
    flex: 1,
  },
  modalScroll: {
    flexGrow: 0,
  },
  modalScrollContent: {
    paddingBottom: 16,
  },
  modalTitulo: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.ink,
    marginBottom: 4,
  },
  modalFecharBotao: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EEF2F7',
  },
  modalInfoCobranca: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E8EDF5',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalInfoTexto: {
    flex: 1,
    minWidth: 0,
  },
  modalInfoLabel: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: '800',
    marginBottom: 4,
  },
  modalInfoVencimento: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: '600',
  },
  modalInfoValor: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.primary,
  },
  modalBotao: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#F0ECFA',
  },
  modalBotaoPrincipal: {
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  modalBotaoPrincipalPix: {
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#00A884',
    borderColor: '#00A884',
  },
  modalBotaoPrincipalTexto: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.surface,
  },
  // Abas Boleto / PIX no resultado
  paymentTabRow: {
    flexDirection: 'row',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.soft,
    padding: 4,
    gap: 4,
    marginBottom: 14,
  },
  paymentTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  paymentTabAtiva: {
    shadowColor: colors.ink,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  paymentTabAtivaBoleto: {
    backgroundColor: colors.primary,
  },
  paymentTabAtivaPix: {
    backgroundColor: colors.credit,
  },
  paymentTabTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.muted,
  },
  paymentTabTextoAtivo: {
    color: colors.surface,
  },
  paymentTabTextoAtivoPix: {
    color: colors.surface,
  },
  // Botão único "Gerar boleto"
  modalBotaoGerar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 2,
  },
  modalBotaoGerarDesabilitado: {
    opacity: 0.6,
  },
  modalBotaoGerarIconeWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBotaoGerarTexto: {
    flex: 1,
  },
  modalBotaoGerarTitulo: {
    fontSize: 15,
    fontWeight: '900',
    color: colors.surface,
  },
  modalBotaoGerarSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.78)',
    marginTop: 1,
  },
  modalBotaoGerarPixBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ECFDF5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  modalBotaoGerarPixBadgeTexto: {
    fontSize: 11,
    fontWeight: '700',
    color: '#00A884',
  },
  modalBotaoIcone: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modalBotaoIconeBoleto: {
    backgroundColor: '#EFF6FF',
  },
  modalBotaoIconePix: {
    backgroundColor: '#ECFDF5',
  },
  modalBotaoTexto: {
    flex: 1,
    minWidth: 0,
  },
  modalBotaoTitulo: {
    fontSize: 15,
    fontWeight: '900',
    color: colors.ink,
    marginBottom: 3,
  },
  modalBloqueioContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    backgroundColor: '#FFFBEB',
    marginBottom: 10,
  },
  modalBloqueioTextoWrap: {
    flex: 1,
    minWidth: 0,
  },
  modalBloqueioTexto: {
    fontSize: 14,
    fontWeight: '800',
    color: '#92400E',
    lineHeight: 19,
  },
  modalBloqueioSubtexto: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: '#A16207',
  },
  modalAcaoIcone: {
    marginRight: 10,
  },
  modalResultadoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalResultadoIcone: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalResultadoHeaderTexto: {
    flex: 1,
    minWidth: 0,
  },
  modalResultadoTitulo: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.muted,
    marginBottom: 2,
  },
  modalResultadoValor: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.ink,
  },
  pixQrWrap: {
    alignSelf: 'center',
    width: 188,
    height: 188,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F0ECFA',
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  pixQrImage: {
    width: 168,
    height: 168,
  },
  pixCodeBox: {
    borderRadius: 10,
    height: 50,
    paddingHorizontal: 12,
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#F0ECFA',
    overflow: 'hidden',
  },
  pixCodeLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '700',
    marginBottom: 2,
  },
  pixCodeValue: {
    fontSize: 11,
    color: colors.ink,
    fontWeight: '600',
    lineHeight: 14,
  },
  modalErro: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
    backgroundColor: '#FEF2F2',
  },
  modalErroTexto: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: colors.debit,
  },
  modalLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  modalLoadingTexto: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.muted,
    marginTop: 12,
  },
  modalBotaoCancelar: {
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F0ECFA',
    backgroundColor: colors.surface,
  },
  modalAcoesFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalBotaoConsultar: {
    flex: 1.45,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    borderColor: colors.primary,
  },
  modalBotaoConsultarTexto: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.primary,
  },
  modalBotaoCancelarSecundario: {
    flex: 1,
    marginTop: 0,
  },
  modalBotaoCancelarTexto: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.ink,
  },
  boletoLinhaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#F0ECFA',
  },
  boletoLinhaTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  boletoLinhaLabel: {
    fontSize: 13,
    color: colors.muted,
    fontWeight: '700',
    marginBottom: 4,
  },
  boletoLinhaValor: {
    fontSize: 12,
    color: colors.ink,
    fontWeight: '700',
    lineHeight: 17,
  },
  boletoCopiarBotao: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  boletoCopiarBotaoTexto: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '800',
  },
  consultaStatusOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  consultaStatusCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 0,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  consultaStatusTopBar: {
    height: 5,
    width: '100%',
    marginBottom: 16,
  },
  consultaStatusTopBarWarning: {
    backgroundColor: '#F59E0B',
  },
  consultaStatusTopBarSucesso: {
    backgroundColor: '#22C55E',
  },
  consultaStatusFecharBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  consultaStatusIconeWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  consultaStatusIconeWrapWarning: {
    backgroundColor: '#FEF3C7',
  },
  consultaStatusIconeWrapSucesso: {
    backgroundColor: '#DCFCE7',
  },
  consultaStatusStatusTexto: {
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 16,
    letterSpacing: 0.1,
  },
  consultaStatusDescricao: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 21,
  },
  consultaStatusVencimento: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.muted,
    textAlign: 'center',
    marginBottom: 10,
  },
  consultaStatusValor: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.ink,
    textAlign: 'center',
    marginBottom: 14,
  },
  consultaStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderWidth: 1,
    marginBottom: 20,
  },
  consultaStatusBadgeTexto: {
    fontSize: 12,
    fontWeight: '900',
  },
  consultaStatusBadgePendente: {
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
  },
  consultaStatusBadgeTextoPendente: {
    color: '#92400E',
  },
  consultaStatusBadgePaga: {
    backgroundColor: '#DCFCE7',
    borderColor: '#BBF7D0',
  },
  consultaStatusBadgeTextoPaga: {
    color: '#166534',
  },
  consultaStatusBadgeAtrasada: {
    backgroundColor: '#FEE2E2',
    borderColor: '#FECACA',
  },
  consultaStatusBadgeTextoAtrasada: {
    color: '#991B1B',
  },
  consultaStatusBadgeCancelada: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  consultaStatusBadgeTextoCancelada: {
    color: '#374151',
  },
  consultaStatusBadgeDefault: {
    backgroundColor: '#EEF2FF',
    borderColor: '#E0E7FF',
  },
  consultaStatusBadgeTextoDefault: {
    color: '#3730A3',
  },
  consultaStatusBotaoFechar: {
    width: '100%',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: colors.primary,
  },
  consultaStatusBotaoFecharWarning: {
    backgroundColor: '#D97706',
  },
  consultaStatusBotaoFecharSucesso: {
    backgroundColor: '#16A34A',
  },
  consultaStatusBotaoFecharTexto: {
    fontSize: 15,
    fontWeight: '900',
    color: colors.surface,
  },
  
  // Telas vazias/erro/loading
  telaVaziaContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20, backgroundColor: '#F6F7FB' },
  telaVaziaTexto: { fontSize: 16, fontWeight: '800', color: colors.ink, marginTop: 16, textAlign: 'center' },
  telaVaziaSubtexto: { fontSize: 14, color: colors.muted, marginTop: 8, textAlign: 'center' },
  botaoTentarNovamente: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 24,
  },
  botaoTentarNovamenteTexto: { color: colors.surface, fontWeight: '800', textAlign: 'center' },
  });
}
